name: release

on:
  push:
    branches: [ "master" ]  # 只有推送到 master 分支时才会触发发布

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: cd v2rayN && ./build.ps1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: v2rayN
        path: |
          ./v2rayN/v2rayN.zip

    - name: Create a tag for release
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        $TagName = "v$(Get-Date -Format 'yyyyMMddHHmmss')"  # 使用 PowerShell 获取当前时间并格式化
        git tag $TagName  # 创建标签
        git push origin $TagName  # 推送标签到远程仓库

    # 使用 git fetch 确保标签已同步
    - name: Ensure tag is pushed
      run: |
        git fetch --tags  # 确保标签被拉取到本地并同步

    # 增加延迟等待 GitHub 完成标签同步
    - name: Wait for GitHub to recognize the tag
      run: sleep 15  # 延迟15秒以确保标签同步

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./v2rayN/v2rayN.zip  # 确保上传的是构建产物
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
