name: release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: cd v2rayN && ./build.ps1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: v2rayN
        path: |
          ./v2rayN/v2rayN.zip

    # 发布构建产物到 GitHub Releases
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./v2rayN/v2rayN.zip  # 指定要发布的文件路径
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 Token 来进行身份验证
