name: release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: cd v2rayN && ./build.ps1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: v2rayN
        path: |
          ./v2rayN/v2rayN.zip

    - name: Create a tag for release
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        $TagName = "v$(Get-Date -Format 'yyyyMMddHHmmss')"  # 使用 PowerShell 获取当前时间并格式化
        git tag $TagName  # 创建标签
        git push origin $TagName  # 推送标签到远程仓库

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./v2rayN/v2rayN.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
